export const collaborateurs = {
  titre: 'Collaborateurs',
  retour: 'Tous les dossiers',
  aide: 'Les collaborateurs rejoignent l’agence avec une adresse de son domaine. Un administrateur peut changer leur rôle ou retirer leur accès.',
  adresseMasquee: 'Adresse hors du domaine de l’agence',
  roles: { admin: 'Administrateur', membre: 'Membre', exclu: 'Accès retiré' },
  action: 'Modification',
  choisir: 'Choisir une action',
  promouvoir: 'Nommer administrateur',
  retrograder: 'Passer membre',
  exclure: 'Retirer l’accès',
  readmettre: 'Autoriser le retour',
  confirmer: 'Je confirme cette modification d’accès.',
  appliquer: 'Appliquer',
  attente: 'Modification…',
  succes: 'Modification enregistrée.',
  readmission:
    'Autoriser le retour permet au collaborateur de rejoindre à nouveau l’agence lors de sa prochaine connexion. Aucun courriel n’est envoyé.',
  session: 'Votre session ne permet pas cette modification.',
  invalide: 'Choisissez une action et confirmez-la.',
  autreAgence: 'L’agence affichée a changé. Rechargez la page.',
  dernierAdmin: 'Nommez d’abord un autre administrateur avant de retirer ce rôle.',
  echec:
    'La modification n’a pas abouti ou la situation a changé. Rechargez la page avant de réessayer.',
  journal: 'Dernières modifications des accès',
  aucun: 'Aucun collaborateur sur cette page.',
  journalVide: 'Aucune modification enregistrée.',
  actions: {
    role: 'Changement de rôle',
    exclusion: 'Accès retiré',
    readmission: 'Retour autorisé',
  },
  operateur: 'Identité non affichée',
  cible: 'Collaborateur',
  par: 'Par',
  page: (n: number) => `Page ${n}`,
  precedente: 'Page précédente',
  suivante: 'Page suivante',
  pagination: 'Pages des collaborateurs',
}
