export const exportsRegistres = {
  titre: 'Exporter le registre',
  aide: 'Téléchargez toutes les pages du registre, dans la limite de 1 000 lignes. Le CSV contient les références, dates et états, sans pièce ni identité des personnes. Les dates sont en UTC. Il constitue une copie ponctuelle, pas une facture.',
  telecharger: 'Télécharger le registre CSV',
  attente: 'Préparation du registre…',
  succes: 'Fichier préparé. Conservez cet export dans un emplacement sécurisé.',
  erreur: 'Le registre est indisponible. Aucun fichier partiel n’a été téléchargé. Réessayez.',
  limite: 'Le registre dépasse 1 000 lignes. Aucun fichier partiel n’a été téléchargé.',
  oui: 'Oui',
  non: 'Non',
  texte: 'Texte : ',
  colonnesArchives: [
    'Référence acte',
    'Modèle',
    'Archivé le (UTC)',
    'Conserver jusqu’au (UTC)',
    'Environnement',
    'Exporté le (UTC)',
  ],
  colonnesReglements: [
    'Référence règlement',
    'Montant EUR',
    'Remboursé EUR',
    'Créé le (UTC)',
    'Payé le (UTC)',
    'Version du tarif',
    'État',
    'Rapprochement à examiner',
    'Exporté le (UTC)',
  ],
} as const
