export const interfaceEspace = {
  agence: 'Espace agence',
  porteur: 'Espace privé',
  accueil: 'Retour à l’accueil',
  navigation: 'Navigation de votre espace',
  tableau: 'Mes dossiers',
  principal: 'Aller au contenu',
  signature: 'Un dossier commun. Des espaces séparés.',
  ouverture: 'On commence ici',
  retrouver: 'Tu as déjà un dossier ?',
  reglageDetails: 'Comprendre ces réglages',
  nouveauDossier: 'Nouveau dossier',
  reglages: 'Réglages',
  navigationDossier: 'Dans ce dossier',
  organisation: 'Organisation du dossier',
  pieces: 'Pièces',
  engagement: 'Engagement',
  decision: 'Décision',
  historique: 'Historique',
  loyer: 'Logement',
  garant: 'Garant',
  paiement: 'Paiement',
  connexion: 'Bienvenue chez vous',
  connexionTitre: 'Votre espace agence',
  connexionTexte:
    'Pas de mot de passe. Recevez un lien de connexion à votre adresse professionnelle pour retrouver vos dossiers.',
  securite: 'Une protection de plus',
  equipe: 'Votre équipe, au même endroit',
  connecteurs: 'Vos outils, reliés au suivi',
  parcours: 'Trois rôles. Une règle : chacun sa place.',
  roles: [
    { nom: 'Locataire', texte: 'Tu ouvres le dossier et tu suis son avancée.', ton: 'mint' },
    { nom: 'Garant', texte: 'Tu déposes tes pièces dans ton espace privé.', ton: 'sun' },
    { nom: 'Agence', texte: 'Vous examinez le dossier dans votre espace.', ton: 'sky' },
  ],
} as const
