export const signature = {
  etiquette: 'Acte de cautionnement',
  lienArchives: 'Archives',
  titre: 'Signature de l’acte',
  preparation: 'Préparer l’acte',
  explication:
    'Déposez le PDF issu de votre modèle validé, avec les informations du dossier et la mention personnelle saisie par le garant. Le garant devra le consulter et l’accepter avant l’envoi en signature.',
  fichier: 'Acte PDF, 4 Mio et 40 pages maximum',
  pdfInvalide:
    'PDF non accepté. Vérifiez qu’il est lisible, non protégé, sans formulaire ni pièce jointe, avec au plus 40 pages non pivotées. Le champ de signature doit tenir entièrement dans la page choisie.',
  placement:
    'Le champ mesure 85 × 37 points. Mesurez sa position depuis le coin supérieur gauche de la page.',
  apercu: 'Afficher la page',
  apercuAttente: 'Préparation de l’aperçu…',
  apercuPret: 'Aperçu prêt. Vérifiez le texte et la position du champ avant de soumettre.',
  apercuErreur: 'Aperçu indisponible. Vérifiez le fichier et la page, puis réessayez.',
  apercuLimite: 'Limite de prévisualisation atteinte. Réessayez plus tard.',
  apercuAide:
    'Cliquez dans la page pour centrer le champ. Au clavier, utilisez les flèches pour le déplacer d’un point, ou Maj avec une flèche pour dix points. Les coordonnées restent modifiables ci-dessous.',
  apercuZone: 'Page de l’acte : placement du champ de signature',
  apercuImage: 'Aperçu visuel de la page choisie du projet',
  apercuChamp: 'Signature',
  apercuHorsPage: 'Le champ dépasse la page. Corrigez ses coordonnées avant de soumettre.',
  apercuConfidentialite:
    'L’aperçu est temporaire et ne modifie pas votre PDF. Consultez aussi l’original pour vérifier son contenu complet.',
  telephone: 'Téléphone du garant, au format international',
  page: 'Page du champ de signature',
  x: 'Position depuis la gauche (points)',
  y: 'Position depuis le haut (points)',
  accordAgence:
    'J’ai vérifié que ce PDF reprend le modèle indiqué, les bonnes parties, les conditions et la mention personnelle du garant.',
  envoyer: 'Soumettre au garant',
  attente: 'Enregistrement en cours…',
  erreur: 'Opération non confirmée. Vérification du suivi nécessaire avant un nouvel essai.',
  indisponible: 'Le parcours de signature n’est pas ouvert sur cet environnement.',
  succes: 'Le projet est disponible pour la validation du garant.',
  consulter: 'Consulter le projet PDF',
  acte: 'Télécharger l’acte signé',
  preuve: 'Télécharger la preuve de signature',
  garant:
    'Lis le PDF, vérifie les parties, les conditions, ta mention personnelle et le téléphone affiché. Cette validation autorise l’envoi chez le prestataire ; elle ne remplace pas ta signature.',
  accordGarant:
    'J’ai consulté le PDF et je confirme son contenu ainsi que mon numéro de téléphone.',
  accepter: 'Valider pour signature',
  refuser: 'Refuser ce projet',
  conserve: 'L’acte et la preuve sont conservés séparément des justificatifs.',
  sandbox: 'Environnement de test : aucune facturation agence ne sera créée.',
  archives: 'Actes et archives',
  modele: 'Modèle',
  etat: 'État',
  telephoneGarant: 'Téléphone utilisé pour la signature',
  echeance: 'Conservation prévue jusqu’au',
  suite: 'Page suivante',
  retour: 'Retour à l’espace agence',
  retourGarant: 'Retour à mon dossier',
  suivi: 'Ouvrir le suivi de l’acte',
  reprendre: 'Reprendre le dépôt du même PDF',
  valide: 'Validation enregistrée.',
  refuse: 'Refus enregistré.',
  aucun: 'Aucun acte disponible.',
  archivesAide:
    'Les actes archivés et leurs preuves de signature sont accessibles depuis cet espace.',
  documents: 'Documents disponibles',
  fournisseur: {
    draft: 'Préparation',
    approval: 'Approbation attendue',
    ongoing: 'Signature attendue',
    paused: 'En pause',
    rejected: 'Demande rejetée',
    declined: 'Signature refusée',
    canceled: 'Demande annulée',
    expired: 'Demande expirée',
    deleted: 'Demande supprimée',
    done: 'Signature terminée',
  } as Record<string, string>,
  traitement: 'Traitement en cours',
  etapes: {
    preparation: 'Préparation du PDF',
    a_valider: 'Validation du garant attendue',
    valide: 'Envoi à préparer',
    document: 'Dépôt du document',
    signataire: 'Préparation du signataire',
    activation: 'Activation à effectuer',
    en_cours: 'Signature en cours',
    archive: 'Acte et preuve archivés',
    refuse: 'Projet refusé',
    incertain: 'Opération à rapprocher',
  } as Record<string, string>,
}
